[2022-03-30 00:03:16,174] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: matchup.run_script 2022-03-29T18:00:00+00:00 [queued]>
[2022-03-30 00:03:16,178] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: matchup.run_script 2022-03-29T18:00:00+00:00 [queued]>
[2022-03-30 00:03:16,178] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-03-30 00:03:16,178] {taskinstance.py:1043} INFO - Starting attempt 4 of 6
[2022-03-30 00:03:16,178] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-03-30 00:03:16,185] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): run_script> on 2022-03-29T18:00:00+00:00
[2022-03-30 00:03:16,188] {standard_task_runner.py:52} INFO - Started process 561237 to run task
[2022-03-30 00:03:16,193] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'matchup', 'run_script', '2022-03-29T18:00:00+00:00', '--job-id', '558', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/matchup.py', '--cfg-path', '/tmp/tmp2xrqlza_', '--error-file', '/tmp/tmpipsn5gy9']
[2022-03-30 00:03:16,194] {standard_task_runner.py:77} INFO - Job 558: Subtask run_script
[2022-03-30 00:03:16,219] {logging_mixin.py:104} INFO - Running <TaskInstance: matchup.run_script 2022-03-29T18:00:00+00:00 [running]> on host 531edfb863fc
[2022-03-30 00:03:16,233] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=r.chesne@gmail.com
AIRFLOW_CTX_DAG_OWNER=Robin
AIRFLOW_CTX_DAG_ID=matchup
AIRFLOW_CTX_TASK_ID=run_script
AIRFLOW_CTX_EXECUTION_DATE=2022-03-29T18:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-29T18:00:00+00:00
[2022-03-30 00:03:16,233] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-03-30 00:03:16,233] {bash.py:158} INFO - Running command: python /app/scripts/main.py
[2022-03-30 00:03:16,242] {bash.py:169} INFO - Output:
[2022-03-30 00:03:19,059] {bash.py:173} INFO - Portugal
[2022-03-30 00:03:19,059] {bash.py:173} INFO - 6058
[2022-03-30 00:03:19,059] {bash.py:173} INFO - Spain
[2022-03-30 00:03:19,059] {bash.py:173} INFO - 26071
[2022-03-30 00:03:19,059] {bash.py:173} INFO - Portugal: CO2 223, mix [('gas', 2291, '38'), ('wind', 1760, '29'), ('hydro', 930, '15')]
[2022-03-30 00:03:19,059] {bash.py:173} INFO - Spain: CO2 266, mix [('gas', 12093, '46'), ('nuclear', 5918, '23'), ('hydro', 3333, '13')]
[2022-03-30 00:03:19,059] {bash.py:173} INFO - Norway
[2022-03-30 00:03:19,059] {bash.py:173} INFO - 17007
[2022-03-30 00:03:19,059] {bash.py:173} INFO - Sweden
[2022-03-30 00:03:19,060] {bash.py:173} INFO - 17341
[2022-03-30 00:03:19,060] {bash.py:173} INFO - Norway: CO2 29, mix [('hydro', 15410, '91'), ('wind', 856, '5'), ('hydro discharge', 373, '2')]
[2022-03-30 00:03:19,060] {bash.py:173} INFO - Sweden: CO2 40, mix [('hydro', 6068, '35'), ('nuclear', 5614, '32'), ('wind', 4078, '24')]
[2022-03-30 00:03:19,060] {bash.py:173} INFO - Traceback (most recent call last):
[2022-03-30 00:03:19,060] {bash.py:173} INFO -   File "/app/scripts/main.py", line 241, in <module>
[2022-03-30 00:03:19,060] {bash.py:173} INFO -     get_matchups()
[2022-03-30 00:03:19,060] {bash.py:173} INFO -   File "/app/scripts/main.py", line 51, in get_matchups
[2022-03-30 00:03:19,060] {bash.py:173} INFO -     get_data(division, country1, country2)
[2022-03-30 00:03:19,060] {bash.py:173} INFO -   File "/app/scripts/main.py", line 199, in get_data
[2022-03-30 00:03:19,060] {bash.py:173} INFO -     co2_country2 = get_co2(country2)
[2022-03-30 00:03:19,060] {bash.py:173} INFO -   File "/app/scripts/main.py", line 73, in get_co2
[2022-03-30 00:03:19,060] {bash.py:173} INFO -     country_consumption_total = get_total_consumption(country)
[2022-03-30 00:03:19,060] {bash.py:173} INFO -   File "/app/scripts/main.py", line 66, in get_total_consumption
[2022-03-30 00:03:19,060] {bash.py:173} INFO -     country_consumption_total.append(sum(res.get('powerConsumptionBreakdown').values()))
[2022-03-30 00:03:19,060] {bash.py:173} INFO - AttributeError: 'NoneType' object has no attribute 'values'
[2022-03-30 00:03:19,091] {bash.py:177} INFO - Command exited with return code 1
[2022-03-30 00:03:19,099] {taskinstance.py:1455} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/app/env/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-03-30 00:03:19,101] {taskinstance.py:1496} INFO - Marking task as UP_FOR_RETRY. dag_id=matchup, task_id=run_script, execution_date=20220329T180000, start_date=20220330T000316, end_date=20220330T000319
[2022-03-30 00:03:19,133] {local_task_job.py:146} INFO - Task exited with return code 1
