[2022-03-24 18:02:13,956] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: matchup.run_script 2022-03-24T12:00:00+00:00 [queued]>
[2022-03-24 18:02:13,961] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: matchup.run_script 2022-03-24T12:00:00+00:00 [queued]>
[2022-03-24 18:02:13,962] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-03-24 18:02:13,962] {taskinstance.py:1043} INFO - Starting attempt 3 of 6
[2022-03-24 18:02:13,962] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-03-24 18:02:13,968] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): run_script> on 2022-03-24T12:00:00+00:00
[2022-03-24 18:02:13,971] {standard_task_runner.py:52} INFO - Started process 486300 to run task
[2022-03-24 18:02:13,978] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'matchup', 'run_script', '2022-03-24T12:00:00+00:00', '--job-id', '465', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/matchup.py', '--cfg-path', '/tmp/tmp_v9juo7q', '--error-file', '/tmp/tmpgf81y90c']
[2022-03-24 18:02:13,979] {standard_task_runner.py:77} INFO - Job 465: Subtask run_script
[2022-03-24 18:02:14,009] {logging_mixin.py:104} INFO - Running <TaskInstance: matchup.run_script 2022-03-24T12:00:00+00:00 [running]> on host 531edfb863fc
[2022-03-24 18:02:14,025] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=r.chesne@gmail.com
AIRFLOW_CTX_DAG_OWNER=Robin
AIRFLOW_CTX_DAG_ID=matchup
AIRFLOW_CTX_TASK_ID=run_script
AIRFLOW_CTX_EXECUTION_DATE=2022-03-24T12:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-24T12:00:00+00:00
[2022-03-24 18:02:14,025] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-03-24 18:02:14,026] {bash.py:158} INFO - Running command: python /app/scripts/main.py
[2022-03-24 18:02:14,032] {bash.py:169} INFO - Output:
[2022-03-24 18:02:18,395] {bash.py:173} INFO - Spain
[2022-03-24 18:02:18,396] {bash.py:173} INFO - 30894
[2022-03-24 18:02:18,396] {bash.py:173} INFO - Italy
[2022-03-24 18:02:18,396] {bash.py:173} INFO - 38855
[2022-03-24 18:02:18,396] {bash.py:173} INFO - Spain: CO2 165, mix [('wind', 8802, '28'), ('gas', 7712, '25'), ('nuclear', 6069, '20')]
[2022-03-24 18:02:18,396] {bash.py:173} INFO - Italy: CO2 385, mix [('gas', 20032, '52'), ('solar', 5583, '14'), ('coal', 3570, '9')]
[2022-03-24 18:02:18,396] {bash.py:173} INFO - Sweden
[2022-03-24 18:02:18,396] {bash.py:173} INFO - 16792
[2022-03-24 18:02:18,396] {bash.py:173} INFO - Norway
[2022-03-24 18:02:18,396] {bash.py:173} INFO - 16779
[2022-03-24 18:02:18,396] {bash.py:173} INFO - Sweden: CO2 41, mix [('hydro', 7895, '47'), ('nuclear', 5295, '32'), ('wind', 2132, '13')]
[2022-03-24 18:02:18,396] {bash.py:173} INFO - Norway: CO2 28, mix [('hydro', 14626, '87'), ('wind', 1537, '9'), ('hydro discharge', 296, '2')]
[2022-03-24 18:02:18,397] {bash.py:173} INFO - Traceback (most recent call last):
[2022-03-24 18:02:18,397] {bash.py:173} INFO -   File "/app/scripts/main.py", line 241, in <module>
[2022-03-24 18:02:18,397] {bash.py:173} INFO -     get_matchups()
[2022-03-24 18:02:18,397] {bash.py:173} INFO -   File "/app/scripts/main.py", line 51, in get_matchups
[2022-03-24 18:02:18,397] {bash.py:173} INFO -     get_data(division, country1, country2)
[2022-03-24 18:02:18,397] {bash.py:173} INFO -   File "/app/scripts/main.py", line 199, in get_data
[2022-03-24 18:02:18,397] {bash.py:173} INFO -     co2_country2 = get_co2(country2)
[2022-03-24 18:02:18,397] {bash.py:173} INFO -   File "/app/scripts/main.py", line 73, in get_co2
[2022-03-24 18:02:18,397] {bash.py:173} INFO -     country_consumption_total = get_total_consumption(country)
[2022-03-24 18:02:18,397] {bash.py:173} INFO -   File "/app/scripts/main.py", line 66, in get_total_consumption
[2022-03-24 18:02:18,397] {bash.py:173} INFO -     country_consumption_total.append(sum(res.get('powerConsumptionBreakdown').values()))
[2022-03-24 18:02:18,397] {bash.py:173} INFO - AttributeError: 'NoneType' object has no attribute 'values'
[2022-03-24 18:02:18,431] {bash.py:177} INFO - Command exited with return code 1
[2022-03-24 18:02:18,440] {taskinstance.py:1455} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/app/env/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-03-24 18:02:18,442] {taskinstance.py:1496} INFO - Marking task as UP_FOR_RETRY. dag_id=matchup, task_id=run_script, execution_date=20220324T120000, start_date=20220324T180213, end_date=20220324T180218
[2022-03-24 18:02:18,484] {local_task_job.py:146} INFO - Task exited with return code 1
