[2022-05-29 06:05:09,700] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: matchup.run_script 2022-05-29T00:00:00+00:00 [queued]>
[2022-05-29 06:05:09,706] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: matchup.run_script 2022-05-29T00:00:00+00:00 [queued]>
[2022-05-29 06:05:09,706] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-05-29 06:05:09,707] {taskinstance.py:1043} INFO - Starting attempt 6 of 6
[2022-05-29 06:05:09,707] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-05-29 06:05:09,715] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): run_script> on 2022-05-29T00:00:00+00:00
[2022-05-29 06:05:09,718] {standard_task_runner.py:52} INFO - Started process 798237 to run task
[2022-05-29 06:05:09,724] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'matchup', 'run_script', '2022-05-29T00:00:00+00:00', '--job-id', '1145', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/matchup.py', '--cfg-path', '/tmp/tmpx91ccclr', '--error-file', '/tmp/tmppm7c8bbr']
[2022-05-29 06:05:09,724] {standard_task_runner.py:77} INFO - Job 1145: Subtask run_script
[2022-05-29 06:05:09,751] {logging_mixin.py:104} INFO - Running <TaskInstance: matchup.run_script 2022-05-29T00:00:00+00:00 [running]> on host 193e33218975
[2022-05-29 06:05:09,766] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=r.chesne@gmail.com
AIRFLOW_CTX_DAG_OWNER=Robin
AIRFLOW_CTX_DAG_ID=matchup
AIRFLOW_CTX_TASK_ID=run_script
AIRFLOW_CTX_EXECUTION_DATE=2022-05-29T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-29T00:00:00+00:00
[2022-05-29 06:05:09,766] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-05-29 06:05:09,766] {bash.py:158} INFO - Running command: python /app/scripts/main.py
[2022-05-29 06:05:09,772] {bash.py:169} INFO - Output:
[2022-05-29 06:05:10,084] {bash.py:173} INFO - Traceback (most recent call last):
[2022-05-29 06:05:10,085] {bash.py:173} INFO -   File "/app/scripts/main.py", line 241, in <module>
[2022-05-29 06:05:10,085] {bash.py:173} INFO -     get_matchups()
[2022-05-29 06:05:10,085] {bash.py:173} INFO -   File "/app/scripts/main.py", line 51, in get_matchups
[2022-05-29 06:05:10,085] {bash.py:173} INFO -     get_data(division, country1, country2)
[2022-05-29 06:05:10,085] {bash.py:173} INFO -   File "/app/scripts/main.py", line 198, in get_data
[2022-05-29 06:05:10,085] {bash.py:173} INFO -     co2_country1 = get_co2(country1)
[2022-05-29 06:05:10,085] {bash.py:173} INFO -   File "/app/scripts/main.py", line 73, in get_co2
[2022-05-29 06:05:10,085] {bash.py:173} INFO -     country_consumption_total = get_total_consumption(country)
[2022-05-29 06:05:10,085] {bash.py:173} INFO -   File "/app/scripts/main.py", line 66, in get_total_consumption
[2022-05-29 06:05:10,085] {bash.py:173} INFO -     country_consumption_total.append(sum(res.get('powerConsumptionBreakdown').values()))
[2022-05-29 06:05:10,085] {bash.py:173} INFO - AttributeError: 'NoneType' object has no attribute 'values'
[2022-05-29 06:05:10,117] {bash.py:177} INFO - Command exited with return code 1
[2022-05-29 06:05:10,125] {taskinstance.py:1455} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/app/env/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-05-29 06:05:10,127] {taskinstance.py:1496} INFO - Marking task as FAILED. dag_id=matchup, task_id=run_script, execution_date=20220529T000000, start_date=20220529T060509, end_date=20220529T060510
[2022-05-29 06:05:10,174] {local_task_job.py:146} INFO - Task exited with return code 1
