[2022-03-15 18:02:11,276] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: matchup.run_script 2022-03-15T12:00:00+00:00 [queued]>
[2022-03-15 18:02:11,280] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: matchup.run_script 2022-03-15T12:00:00+00:00 [queued]>
[2022-03-15 18:02:11,280] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 18:02:11,280] {taskinstance.py:1043} INFO - Starting attempt 3 of 6
[2022-03-15 18:02:11,280] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 18:02:11,287] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): run_script> on 2022-03-15T12:00:00+00:00
[2022-03-15 18:02:11,290] {standard_task_runner.py:52} INFO - Started process 358174 to run task
[2022-03-15 18:02:11,299] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'matchup', 'run_script', '2022-03-15T12:00:00+00:00', '--job-id', '324', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/matchup.py', '--cfg-path', '/tmp/tmpy7jfve5e', '--error-file', '/tmp/tmpsd77u0y6']
[2022-03-15 18:02:11,300] {standard_task_runner.py:77} INFO - Job 324: Subtask run_script
[2022-03-15 18:02:11,330] {logging_mixin.py:104} INFO - Running <TaskInstance: matchup.run_script 2022-03-15T12:00:00+00:00 [running]> on host 531edfb863fc
[2022-03-15 18:02:11,350] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=r.chesne@gmail.com
AIRFLOW_CTX_DAG_OWNER=Robin
AIRFLOW_CTX_DAG_ID=matchup
AIRFLOW_CTX_TASK_ID=run_script
AIRFLOW_CTX_EXECUTION_DATE=2022-03-15T12:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-15T12:00:00+00:00
[2022-03-15 18:02:11,351] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-03-15 18:02:11,351] {bash.py:158} INFO - Running command: python /app/scripts/main.py
[2022-03-15 18:02:11,360] {bash.py:169} INFO - Output:
[2022-03-15 18:02:14,972] {bash.py:173} INFO - Italy
[2022-03-15 18:02:14,972] {bash.py:173} INFO - 41087
[2022-03-15 18:02:14,972] {bash.py:173} INFO - Portugal
[2022-03-15 18:02:14,972] {bash.py:173} INFO - 3986
[2022-03-15 18:02:14,972] {bash.py:173} INFO - Italy: CO2 395, mix [('gas', 24568, '60'), ('solar', 3325, '8'), ('unknown', 2963, '7')]
[2022-03-15 18:02:14,972] {bash.py:173} INFO - Portugal: CO2 209, mix [('gas', 1393, '35'), ('wind', 1086, '27'), ('hydro', 902, '23')]
[2022-03-15 18:02:14,972] {bash.py:173} INFO - Denmark
[2022-03-15 18:02:14,972] {bash.py:173} INFO - 4541
[2022-03-15 18:02:14,972] {bash.py:173} INFO - Finland
[2022-03-15 18:02:14,972] {bash.py:173} INFO - 10272
[2022-03-15 18:02:14,972] {bash.py:173} INFO - Denmark: CO2 277, mix [('hydro', 1495, '33'), ('coal', 972, '21'), ('biomass', 788, '17')]
[2022-03-15 18:02:14,972] {bash.py:173} INFO - Finland: CO2 187, mix [('nuclear', 3643, '35'), ('hydro', 2311, '22'), ('coal', 1271, '12')]
[2022-03-15 18:02:14,973] {bash.py:173} INFO - Traceback (most recent call last):
[2022-03-15 18:02:14,973] {bash.py:173} INFO -   File "/app/scripts/main.py", line 241, in <module>
[2022-03-15 18:02:14,973] {bash.py:173} INFO -     get_matchups()
[2022-03-15 18:02:14,973] {bash.py:173} INFO -   File "/app/scripts/main.py", line 51, in get_matchups
[2022-03-15 18:02:14,973] {bash.py:173} INFO -     get_data(division, country1, country2)
[2022-03-15 18:02:14,973] {bash.py:173} INFO -   File "/app/scripts/main.py", line 198, in get_data
[2022-03-15 18:02:14,973] {bash.py:173} INFO -     co2_country1 = get_co2(country1)
[2022-03-15 18:02:14,973] {bash.py:173} INFO -   File "/app/scripts/main.py", line 73, in get_co2
[2022-03-15 18:02:14,973] {bash.py:173} INFO -     country_consumption_total = get_total_consumption(country)
[2022-03-15 18:02:14,973] {bash.py:173} INFO -   File "/app/scripts/main.py", line 66, in get_total_consumption
[2022-03-15 18:02:14,973] {bash.py:173} INFO -     country_consumption_total.append(sum(res.get('powerConsumptionBreakdown').values()))
[2022-03-15 18:02:14,973] {bash.py:173} INFO - AttributeError: 'NoneType' object has no attribute 'values'
[2022-03-15 18:02:15,021] {bash.py:177} INFO - Command exited with return code 1
[2022-03-15 18:02:15,028] {taskinstance.py:1455} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/app/env/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-03-15 18:02:15,030] {taskinstance.py:1496} INFO - Marking task as UP_FOR_RETRY. dag_id=matchup, task_id=run_script, execution_date=20220315T120000, start_date=20220315T180211, end_date=20220315T180215
[2022-03-15 18:02:15,081] {local_task_job.py:146} INFO - Task exited with return code 1
