[2022-03-06 00:00:04,312] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: matchup.run_script 2022-03-05T18:00:00+00:00 [queued]>
[2022-03-06 00:00:04,317] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: matchup.run_script 2022-03-05T18:00:00+00:00 [queued]>
[2022-03-06 00:00:04,317] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-03-06 00:00:04,317] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2022-03-06 00:00:04,317] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-03-06 00:00:04,328] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): run_script> on 2022-03-05T18:00:00+00:00
[2022-03-06 00:00:04,332] {standard_task_runner.py:52} INFO - Started process 219206 to run task
[2022-03-06 00:00:04,339] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'matchup', 'run_script', '2022-03-05T18:00:00+00:00', '--job-id', '156', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/matchup.py', '--cfg-path', '/tmp/tmpps29p8vv', '--error-file', '/tmp/tmppq7qf93r']
[2022-03-06 00:00:04,340] {standard_task_runner.py:77} INFO - Job 156: Subtask run_script
[2022-03-06 00:00:04,390] {logging_mixin.py:104} INFO - Running <TaskInstance: matchup.run_script 2022-03-05T18:00:00+00:00 [running]> on host 531edfb863fc
[2022-03-06 00:00:04,440] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=r.chesne@gmail.com
AIRFLOW_CTX_DAG_OWNER=Robin
AIRFLOW_CTX_DAG_ID=matchup
AIRFLOW_CTX_TASK_ID=run_script
AIRFLOW_CTX_EXECUTION_DATE=2022-03-05T18:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-05T18:00:00+00:00
[2022-03-06 00:00:04,441] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-03-06 00:00:04,442] {bash.py:158} INFO - Running command: python /app/scripts/main.py
[2022-03-06 00:00:04,452] {bash.py:169} INFO - Output:
[2022-03-06 00:00:09,622] {bash.py:173} INFO - Spain: CO2 171, mix [('nuclear', 8353, '31'), ('wind', 7308, '27'), ('gas', 6109, '22')]
[2022-03-06 00:00:09,623] {bash.py:173} INFO - Italy: CO2 349, mix [('gas', 11536, '38'), ('wind', 5186, '17'), ('hydro', 3619, '12')]
[2022-03-06 00:00:09,624] {bash.py:173} INFO - Finland: CO2 174, mix [('nuclear', 3191, '34'), ('wind', 1917, '20'), ('hydro', 1507, '16')]
[2022-03-06 00:00:09,624] {bash.py:173} INFO - Norway: CO2 29, mix [('hydro', 14149, '83'), ('wind', 2004, '12'), ('hydro discharge', 416, '2')]
[2022-03-06 00:00:09,624] {bash.py:173} INFO - Traceback (most recent call last):
[2022-03-06 00:00:09,624] {bash.py:173} INFO -   File "/app/scripts/main.py", line 235, in <module>
[2022-03-06 00:00:09,624] {bash.py:173} INFO -     get_matchups()
[2022-03-06 00:00:09,624] {bash.py:173} INFO -   File "/app/scripts/main.py", line 51, in get_matchups
[2022-03-06 00:00:09,624] {bash.py:173} INFO -     get_data(division, country1, country2)
[2022-03-06 00:00:09,624] {bash.py:173} INFO -   File "/app/scripts/main.py", line 194, in get_data
[2022-03-06 00:00:09,625] {bash.py:173} INFO -     co2_country2 = get_co2(country2)
[2022-03-06 00:00:09,625] {bash.py:173} INFO -   File "/app/scripts/main.py", line 76, in get_co2
[2022-03-06 00:00:09,625] {bash.py:173} INFO -     country_co2_levels_cleaned.append(co2_level*production_level)
[2022-03-06 00:00:09,625] {bash.py:173} INFO - TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
[2022-03-06 00:00:09,676] {bash.py:177} INFO - Command exited with return code 1
[2022-03-06 00:00:09,684] {taskinstance.py:1455} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/app/env/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-03-06 00:00:09,688] {taskinstance.py:1496} INFO - Marking task as UP_FOR_RETRY. dag_id=matchup, task_id=run_script, execution_date=20220305T180000, start_date=20220306T000004, end_date=20220306T000009
[2022-03-06 00:00:09,736] {local_task_job.py:146} INFO - Task exited with return code 1
