[2022-03-24 00:00:03,453] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: matchup.run_script 2022-03-23T18:00:00+00:00 [queued]>
[2022-03-24 00:00:03,457] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: matchup.run_script 2022-03-23T18:00:00+00:00 [queued]>
[2022-03-24 00:00:03,457] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-03-24 00:00:03,457] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2022-03-24 00:00:03,457] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-03-24 00:00:03,464] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): run_script> on 2022-03-23T18:00:00+00:00
[2022-03-24 00:00:03,467] {standard_task_runner.py:52} INFO - Started process 475516 to run task
[2022-03-24 00:00:03,475] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'matchup', 'run_script', '2022-03-23T18:00:00+00:00', '--job-id', '442', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/matchup.py', '--cfg-path', '/tmp/tmpsh2j057n', '--error-file', '/tmp/tmp1fpnzx07']
[2022-03-24 00:00:03,476] {standard_task_runner.py:77} INFO - Job 442: Subtask run_script
[2022-03-24 00:00:03,504] {logging_mixin.py:104} INFO - Running <TaskInstance: matchup.run_script 2022-03-23T18:00:00+00:00 [running]> on host 531edfb863fc
[2022-03-24 00:00:03,524] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=r.chesne@gmail.com
AIRFLOW_CTX_DAG_OWNER=Robin
AIRFLOW_CTX_DAG_ID=matchup
AIRFLOW_CTX_TASK_ID=run_script
AIRFLOW_CTX_EXECUTION_DATE=2022-03-23T18:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-23T18:00:00+00:00
[2022-03-24 00:00:03,524] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-03-24 00:00:03,525] {bash.py:158} INFO - Running command: python /app/scripts/main.py
[2022-03-24 00:00:03,532] {bash.py:169} INFO - Output:
[2022-03-24 00:00:06,853] {bash.py:173} INFO - Spain
[2022-03-24 00:00:06,854] {bash.py:173} INFO - 29064
[2022-03-24 00:00:06,854] {bash.py:173} INFO - Italy
[2022-03-24 00:00:06,854] {bash.py:173} INFO - 33090
[2022-03-24 00:00:06,854] {bash.py:173} INFO - Spain: CO2 166, mix [('wind', 11109, '38'), ('gas', 6693, '23'), ('nuclear', 5793, '20')]
[2022-03-24 00:00:06,854] {bash.py:173} INFO - Italy: CO2 466, mix [('gas', 22204, '67'), ('coal', 3285, '10'), ('unknown', 2168, '7')]
[2022-03-24 00:00:06,854] {bash.py:173} INFO - Denmark
[2022-03-24 00:00:06,854] {bash.py:173} INFO - 3944
[2022-03-24 00:00:06,855] {bash.py:173} INFO - Finland
[2022-03-24 00:00:06,855] {bash.py:173} INFO - 8330
[2022-03-24 00:00:06,855] {bash.py:173} INFO - Denmark: CO2 287, mix [('hydro', 1094, '28'), ('coal', 862, '22'), ('biomass', 513, '13')]
[2022-03-24 00:00:06,855] {bash.py:173} INFO - Finland: CO2 129, mix [('nuclear', 3127, '38'), ('wind', 2769, '33'), ('unknown', 650, '8')]
[2022-03-24 00:00:06,855] {bash.py:173} INFO - Traceback (most recent call last):
[2022-03-24 00:00:06,855] {bash.py:173} INFO -   File "/app/scripts/main.py", line 241, in <module>
[2022-03-24 00:00:06,855] {bash.py:173} INFO -     get_matchups()
[2022-03-24 00:00:06,855] {bash.py:173} INFO -   File "/app/scripts/main.py", line 51, in get_matchups
[2022-03-24 00:00:06,855] {bash.py:173} INFO -     get_data(division, country1, country2)
[2022-03-24 00:00:06,856] {bash.py:173} INFO -   File "/app/scripts/main.py", line 198, in get_data
[2022-03-24 00:00:06,856] {bash.py:173} INFO -     co2_country1 = get_co2(country1)
[2022-03-24 00:00:06,856] {bash.py:173} INFO -   File "/app/scripts/main.py", line 73, in get_co2
[2022-03-24 00:00:06,856] {bash.py:173} INFO -     country_consumption_total = get_total_consumption(country)
[2022-03-24 00:00:06,856] {bash.py:173} INFO -   File "/app/scripts/main.py", line 66, in get_total_consumption
[2022-03-24 00:00:06,856] {bash.py:173} INFO -     country_consumption_total.append(sum(res.get('powerConsumptionBreakdown').values()))
[2022-03-24 00:00:06,856] {bash.py:173} INFO - AttributeError: 'NoneType' object has no attribute 'values'
[2022-03-24 00:00:06,893] {bash.py:177} INFO - Command exited with return code 1
[2022-03-24 00:00:06,901] {taskinstance.py:1455} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/app/env/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-03-24 00:00:06,903] {taskinstance.py:1496} INFO - Marking task as UP_FOR_RETRY. dag_id=matchup, task_id=run_script, execution_date=20220323T180000, start_date=20220324T000003, end_date=20220324T000006
[2022-03-24 00:00:06,935] {local_task_job.py:146} INFO - Task exited with return code 1
