[2022-03-08 06:01:08,845] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: matchup.run_script 2022-03-08T00:00:00+00:00 [queued]>
[2022-03-08 06:01:08,852] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: matchup.run_script 2022-03-08T00:00:00+00:00 [queued]>
[2022-03-08 06:01:08,852] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-03-08 06:01:08,852] {taskinstance.py:1043} INFO - Starting attempt 2 of 6
[2022-03-08 06:01:08,852] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-03-08 06:01:08,862] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): run_script> on 2022-03-08T00:00:00+00:00
[2022-03-08 06:01:08,865] {standard_task_runner.py:52} INFO - Started process 251378 to run task
[2022-03-08 06:01:08,872] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'matchup', 'run_script', '2022-03-08T00:00:00+00:00', '--job-id', '210', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/matchup.py', '--cfg-path', '/tmp/tmpzb_u0quh', '--error-file', '/tmp/tmp3pqhqqfg']
[2022-03-08 06:01:08,872] {standard_task_runner.py:77} INFO - Job 210: Subtask run_script
[2022-03-08 06:01:08,922] {logging_mixin.py:104} INFO - Running <TaskInstance: matchup.run_script 2022-03-08T00:00:00+00:00 [running]> on host 531edfb863fc
[2022-03-08 06:01:08,959] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=r.chesne@gmail.com
AIRFLOW_CTX_DAG_OWNER=Robin
AIRFLOW_CTX_DAG_ID=matchup
AIRFLOW_CTX_TASK_ID=run_script
AIRFLOW_CTX_EXECUTION_DATE=2022-03-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-08T00:00:00+00:00
[2022-03-08 06:01:08,959] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-03-08 06:01:08,960] {bash.py:158} INFO - Running command: python /app/scripts/main.py
[2022-03-08 06:01:08,969] {bash.py:169} INFO - Output:
[2022-03-08 06:01:10,784] {bash.py:173} INFO - Traceback (most recent call last):
[2022-03-08 06:01:10,784] {bash.py:173} INFO -   File "/app/scripts/main.py", line 235, in <module>
[2022-03-08 06:01:10,784] {bash.py:173} INFO -     get_matchups()
[2022-03-08 06:01:10,784] {bash.py:173} INFO -   File "/app/scripts/main.py", line 51, in get_matchups
[2022-03-08 06:01:10,784] {bash.py:173} INFO -     get_data(division, country1, country2)
[2022-03-08 06:01:10,784] {bash.py:173} INFO -   File "/app/scripts/main.py", line 196, in get_data
[2022-03-08 06:01:10,784] {bash.py:173} INFO -     mix_country2 = get_mix(country2)
[2022-03-08 06:01:10,784] {bash.py:173} INFO -   File "/app/scripts/main.py", line 104, in get_mix
[2022-03-08 06:01:10,784] {bash.py:173} INFO -     mix['total_consumption'] += res.get('powerConsumptionTotal')
[2022-03-08 06:01:10,784] {bash.py:173} INFO - TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
[2022-03-08 06:01:10,863] {bash.py:177} INFO - Command exited with return code 1
[2022-03-08 06:01:10,874] {taskinstance.py:1455} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/app/env/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-03-08 06:01:10,877] {taskinstance.py:1496} INFO - Marking task as UP_FOR_RETRY. dag_id=matchup, task_id=run_script, execution_date=20220308T000000, start_date=20220308T060108, end_date=20220308T060110
[2022-03-08 06:01:10,937] {local_task_job.py:146} INFO - Task exited with return code 1
