[2022-04-06 18:02:11,531] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: matchup.run_script 2022-04-06T12:00:00+00:00 [queued]>
[2022-04-06 18:02:11,535] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: matchup.run_script 2022-04-06T12:00:00+00:00 [queued]>
[2022-04-06 18:02:11,535] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-04-06 18:02:11,535] {taskinstance.py:1043} INFO - Starting attempt 3 of 6
[2022-04-06 18:02:11,535] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-04-06 18:02:11,542] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): run_script> on 2022-04-06T12:00:00+00:00
[2022-04-06 18:02:11,545] {standard_task_runner.py:52} INFO - Started process 46727 to run task
[2022-04-06 18:02:11,549] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'matchup', 'run_script', '2022-04-06T12:00:00+00:00', '--job-id', '69', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/matchup.py', '--cfg-path', '/tmp/tmpety1ztjq', '--error-file', '/tmp/tmpomtfx9tf']
[2022-04-06 18:02:11,550] {standard_task_runner.py:77} INFO - Job 69: Subtask run_script
[2022-04-06 18:02:11,582] {logging_mixin.py:104} INFO - Running <TaskInstance: matchup.run_script 2022-04-06T12:00:00+00:00 [running]> on host 193e33218975
[2022-04-06 18:02:11,600] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=r.chesne@gmail.com
AIRFLOW_CTX_DAG_OWNER=Robin
AIRFLOW_CTX_DAG_ID=matchup
AIRFLOW_CTX_TASK_ID=run_script
AIRFLOW_CTX_EXECUTION_DATE=2022-04-06T12:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-06T12:00:00+00:00
[2022-04-06 18:02:11,600] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-04-06 18:02:11,601] {bash.py:158} INFO - Running command: python /app/scripts/main.py
[2022-04-06 18:02:11,609] {bash.py:169} INFO - Output:
[2022-04-06 18:02:15,082] {bash.py:173} INFO - Italy
[2022-04-06 18:02:15,083] {bash.py:173} INFO - 37985
[2022-04-06 18:02:15,083] {bash.py:173} INFO - Spain
[2022-04-06 18:02:15,083] {bash.py:173} INFO - 29502
[2022-04-06 18:02:15,083] {bash.py:173} INFO - Italy: CO2 384, mix [('gas', 20417, '54'), ('solar', 3302, '9'), ('coal', 3264, '9')]
[2022-04-06 18:02:15,083] {bash.py:173} INFO - Spain: CO2 142, mix [('solar', 9212, '31'), ('wind', 7502, '25'), ('nuclear', 4808, '16')]
[2022-04-06 18:02:15,083] {bash.py:173} INFO - Denmark
[2022-04-06 18:02:15,083] {bash.py:173} INFO - 5183
[2022-04-06 18:02:15,083] {bash.py:173} INFO - Sweden
[2022-04-06 18:02:15,083] {bash.py:173} INFO - 19861
[2022-04-06 18:02:15,083] {bash.py:173} INFO - Denmark: CO2 122, mix [('wind', 3711, '72'), ('biomass', 605, '12'), ('coal', 427, '8')]
[2022-04-06 18:02:15,083] {bash.py:173} INFO - Sweden: CO2 50, mix [('hydro', 8108, '41'), ('nuclear', 6339, '32'), ('wind', 3275, '16')]
[2022-04-06 18:02:15,083] {bash.py:173} INFO - Traceback (most recent call last):
[2022-04-06 18:02:15,084] {bash.py:173} INFO -   File "/app/scripts/main.py", line 241, in <module>
[2022-04-06 18:02:15,084] {bash.py:173} INFO -     get_matchups()
[2022-04-06 18:02:15,084] {bash.py:173} INFO -   File "/app/scripts/main.py", line 51, in get_matchups
[2022-04-06 18:02:15,084] {bash.py:173} INFO -     get_data(division, country1, country2)
[2022-04-06 18:02:15,084] {bash.py:173} INFO -   File "/app/scripts/main.py", line 198, in get_data
[2022-04-06 18:02:15,084] {bash.py:173} INFO -     co2_country1 = get_co2(country1)
[2022-04-06 18:02:15,084] {bash.py:173} INFO -   File "/app/scripts/main.py", line 73, in get_co2
[2022-04-06 18:02:15,084] {bash.py:173} INFO -     country_consumption_total = get_total_consumption(country)
[2022-04-06 18:02:15,084] {bash.py:173} INFO -   File "/app/scripts/main.py", line 66, in get_total_consumption
[2022-04-06 18:02:15,084] {bash.py:173} INFO -     country_consumption_total.append(sum(res.get('powerConsumptionBreakdown').values()))
[2022-04-06 18:02:15,084] {bash.py:173} INFO - AttributeError: 'NoneType' object has no attribute 'values'
[2022-04-06 18:02:15,117] {bash.py:177} INFO - Command exited with return code 1
[2022-04-06 18:02:15,126] {taskinstance.py:1455} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/app/env/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-04-06 18:02:15,128] {taskinstance.py:1496} INFO - Marking task as UP_FOR_RETRY. dag_id=matchup, task_id=run_script, execution_date=20220406T120000, start_date=20220406T180211, end_date=20220406T180215
[2022-04-06 18:02:15,176] {local_task_job.py:146} INFO - Task exited with return code 1
