[2022-03-17 12:02:14,440] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: matchup.run_script 2022-03-17T06:00:00+00:00 [queued]>
[2022-03-17 12:02:14,444] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: matchup.run_script 2022-03-17T06:00:00+00:00 [queued]>
[2022-03-17 12:02:14,444] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-03-17 12:02:14,444] {taskinstance.py:1043} INFO - Starting attempt 3 of 6
[2022-03-17 12:02:14,444] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-03-17 12:02:14,452] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): run_script> on 2022-03-17T06:00:00+00:00
[2022-03-17 12:02:14,456] {standard_task_runner.py:52} INFO - Started process 383109 to run task
[2022-03-17 12:02:14,462] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'matchup', 'run_script', '2022-03-17T06:00:00+00:00', '--job-id', '357', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/matchup.py', '--cfg-path', '/tmp/tmpyq48q_k3', '--error-file', '/tmp/tmplm6_4xpn']
[2022-03-17 12:02:14,462] {standard_task_runner.py:77} INFO - Job 357: Subtask run_script
[2022-03-17 12:02:14,488] {logging_mixin.py:104} INFO - Running <TaskInstance: matchup.run_script 2022-03-17T06:00:00+00:00 [running]> on host 531edfb863fc
[2022-03-17 12:02:14,507] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=r.chesne@gmail.com
AIRFLOW_CTX_DAG_OWNER=Robin
AIRFLOW_CTX_DAG_ID=matchup
AIRFLOW_CTX_TASK_ID=run_script
AIRFLOW_CTX_EXECUTION_DATE=2022-03-17T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-17T06:00:00+00:00
[2022-03-17 12:02:14,507] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-03-17 12:02:14,508] {bash.py:158} INFO - Running command: python /app/scripts/main.py
[2022-03-17 12:02:14,516] {bash.py:169} INFO - Output:
[2022-03-17 12:02:18,709] {bash.py:173} INFO - Italy
[2022-03-17 12:02:18,710] {bash.py:173} INFO - 42085
[2022-03-17 12:02:18,710] {bash.py:173} INFO - Spain
[2022-03-17 12:02:18,710] {bash.py:173} INFO - 31688
[2022-03-17 12:02:18,710] {bash.py:173} INFO - Italy: CO2 358, mix [('gas', 20440, '49'), ('solar', 5136, '12'), ('coal', 3171, '8')]
[2022-03-17 12:02:18,710] {bash.py:173} INFO - Spain: CO2 130, mix [('wind', 13981, '44'), ('nuclear', 5543, '17'), ('gas', 4641, '15')]
[2022-03-17 12:02:18,710] {bash.py:173} INFO - Norway
[2022-03-17 12:02:18,710] {bash.py:173} INFO - 18703
[2022-03-17 12:02:18,710] {bash.py:173} INFO - Finland
[2022-03-17 12:02:18,710] {bash.py:173} INFO - 9241
[2022-03-17 12:02:18,710] {bash.py:173} INFO - Norway: CO2 31, mix [('hydro', 14915, '80'), ('wind', 3233, '17'), ('hydro discharge', 157, '1')]
[2022-03-17 12:02:18,710] {bash.py:173} INFO - Finland: CO2 159, mix [('nuclear', 3357, '36'), ('hydro', 2096, '23'), ('wind', 1299, '14')]
[2022-03-17 12:02:18,710] {bash.py:173} INFO - Traceback (most recent call last):
[2022-03-17 12:02:18,710] {bash.py:173} INFO -   File "/app/scripts/main.py", line 241, in <module>
[2022-03-17 12:02:18,710] {bash.py:173} INFO -     get_matchups()
[2022-03-17 12:02:18,711] {bash.py:173} INFO -   File "/app/scripts/main.py", line 51, in get_matchups
[2022-03-17 12:02:18,711] {bash.py:173} INFO -     get_data(division, country1, country2)
[2022-03-17 12:02:18,711] {bash.py:173} INFO -   File "/app/scripts/main.py", line 198, in get_data
[2022-03-17 12:02:18,711] {bash.py:173} INFO -     co2_country1 = get_co2(country1)
[2022-03-17 12:02:18,711] {bash.py:173} INFO -   File "/app/scripts/main.py", line 73, in get_co2
[2022-03-17 12:02:18,711] {bash.py:173} INFO -     country_consumption_total = get_total_consumption(country)
[2022-03-17 12:02:18,711] {bash.py:173} INFO -   File "/app/scripts/main.py", line 66, in get_total_consumption
[2022-03-17 12:02:18,711] {bash.py:173} INFO -     country_consumption_total.append(sum(res.get('powerConsumptionBreakdown').values()))
[2022-03-17 12:02:18,711] {bash.py:173} INFO - AttributeError: 'NoneType' object has no attribute 'values'
[2022-03-17 12:02:18,746] {bash.py:177} INFO - Command exited with return code 1
[2022-03-17 12:02:18,754] {taskinstance.py:1455} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/app/env/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-03-17 12:02:18,757] {taskinstance.py:1496} INFO - Marking task as UP_FOR_RETRY. dag_id=matchup, task_id=run_script, execution_date=20220317T060000, start_date=20220317T120214, end_date=20220317T120218
[2022-03-17 12:02:18,809] {local_task_job.py:146} INFO - Task exited with return code 1
