[2022-03-07 19:06:31,544] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: matchup.run_script 2022-03-07T19:04:21.179507+00:00 [queued]>
[2022-03-07 19:06:31,550] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: matchup.run_script 2022-03-07T19:04:21.179507+00:00 [queued]>
[2022-03-07 19:06:31,551] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-03-07 19:06:31,551] {taskinstance.py:1043} INFO - Starting attempt 3 of 6
[2022-03-07 19:06:31,551] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-03-07 19:06:31,561] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): run_script> on 2022-03-07T19:04:21.179507+00:00
[2022-03-07 19:06:31,566] {standard_task_runner.py:52} INFO - Started process 244804 to run task
[2022-03-07 19:06:31,573] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'matchup', 'run_script', '2022-03-07T19:04:21.179507+00:00', '--job-id', '190', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/matchup.py', '--cfg-path', '/tmp/tmp0zg8s_6k', '--error-file', '/tmp/tmpbtv9gxzy']
[2022-03-07 19:06:31,574] {standard_task_runner.py:77} INFO - Job 190: Subtask run_script
[2022-03-07 19:06:31,607] {logging_mixin.py:104} INFO - Running <TaskInstance: matchup.run_script 2022-03-07T19:04:21.179507+00:00 [running]> on host 531edfb863fc
[2022-03-07 19:06:31,630] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=r.chesne@gmail.com
AIRFLOW_CTX_DAG_OWNER=Robin
AIRFLOW_CTX_DAG_ID=matchup
AIRFLOW_CTX_TASK_ID=run_script
AIRFLOW_CTX_EXECUTION_DATE=2022-03-07T19:04:21.179507+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-07T19:04:21.179507+00:00
[2022-03-07 19:06:31,630] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-03-07 19:06:31,631] {bash.py:158} INFO - Running command: python /app/scripts/main.py
[2022-03-07 19:06:31,638] {bash.py:169} INFO - Output:
[2022-03-07 19:06:33,033] {bash.py:173} INFO - Traceback (most recent call last):
[2022-03-07 19:06:33,033] {bash.py:173} INFO -   File "/app/scripts/main.py", line 235, in <module>
[2022-03-07 19:06:33,034] {bash.py:173} INFO -     get_matchups()
[2022-03-07 19:06:33,034] {bash.py:173} INFO -   File "/app/scripts/main.py", line 51, in get_matchups
[2022-03-07 19:06:33,034] {bash.py:173} INFO -     get_data(division, country1, country2)
[2022-03-07 19:06:33,034] {bash.py:173} INFO -   File "/app/scripts/main.py", line 194, in get_data
[2022-03-07 19:06:33,034] {bash.py:173} INFO -     co2_country2 = get_co2(country2)
[2022-03-07 19:06:33,034] {bash.py:173} INFO -   File "/app/scripts/main.py", line 76, in get_co2
[2022-03-07 19:06:33,034] {bash.py:173} INFO -     country_co2_levels_cleaned.append(co2_level*production_level)
[2022-03-07 19:06:33,034] {bash.py:173} INFO - TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
[2022-03-07 19:06:33,093] {bash.py:177} INFO - Command exited with return code 1
[2022-03-07 19:06:33,103] {taskinstance.py:1455} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/app/env/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-03-07 19:06:33,105] {taskinstance.py:1496} INFO - Marking task as UP_FOR_RETRY. dag_id=matchup, task_id=run_script, execution_date=20220307T190421, start_date=20220307T190631, end_date=20220307T190633
[2022-03-07 19:06:33,148] {local_task_job.py:146} INFO - Task exited with return code 1
